# Generated by Django 5.2.4 on 2025-07-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('permanent', 'Permanent'), ('temporaire', 'Temporaire')], max_length=10)),
                ('date_embauche', models.DateField()),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
