# Generated by Django 5.2.4 on 2025-07-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_salaire_journalier_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
    ]
