# Generated by Django 5.1.6 on 2025-08-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_date_embauche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salaire_journalier',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
