# Generated by Django 5.1.6 on 2025-08-02 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('poste', models.CharField(default='Agent de pointage', max_length=50)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_pointage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent de pointage',
                'verbose_name_plural': 'Agents de pointage',
                'ordering': ['nom_complet'],
            },
        ),
    ]
